CNT3        EQU   3FD6H
APORT3   EQU   3FD0H
BPORT3   EQU   3FD2H
CODE       SEGMENT  
         ASSUME   CS:CODE, DS:CODE
         ORG   0

START:   MOV   SP,4000H
                MOV   AL,90H
                MOV   DX,CNT3
                OUT   DX,AL

J2:	MOV	AH,3		;run 3 times

MAIN:	MOV	AL,01H		;4 bit LED left shift
	CALL	OUTPUT
	ROL	AL,1
	CALL	OUTPUT
	ROL	AL,1
	CALL	OUTPUT
	ROL	AL,1
	CALL	OUTPUT
	DEC	AH
	JNZ	MAIN

	MOV	AL,08H		;delay 2s instruction
	CALL	OUTPUT
	MOV	AL,08H
	CALL	OUTPUT
	MOV	AL,08H
	CALL	OUTPUT
	MOV	AL,08H
	CALL	OUTPUT


J1:	MOV	AH,6		;run 6 times

J3:	MOV	AL,08H		;4 bit LED right shift
	CALL	OUTPUT
	ROR	AL,1
	CALL	OUTPUT
	ROR	AL,1
	CALL	OUTPUT
	ROR	AL,1
	CALL	OUTPUT
	DEC	AH
	JNZ	J3

	MOV	AL,01H		;delay 2s instruction
	CALL	OUTPUT
	MOV	AL,01H	
	CALL	OUTPUT
	MOV	AL,01H	
	CALL	OUTPUT
	MOV	AL,01H	
	CALL	OUTPUT

	JMP	J2

OUTPUT:	MOV	DX,BPORT3
	OUT	DX,AL
	MOV	CX,9000H
	LOOP	$
	RET

CODE	ENDS
	END	START
